query GetSaleVolume($date: timestamp!, $kind: String) {
  nft_activities_aggregate(
    where: { timestamp: { _gte: $date }, kind: { _eq: $kind } }
  ) {
    aggregate {
      sum {
        price
      }
    }
  }
}
